// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodHqctL40j39zl9cw09HK0A9pMBwvKGs',
    appId: '1:39414070165:web:5edf088622b733065e149c',
    messagingSenderId: '39414070165',
    projectId: 'monitoreo-apicola',
    authDomain: 'monitoreo-apicola.firebaseapp.com',
    storageBucket: 'monitoreo-apicola.firebasestorage.app',
    measurementId: 'G-64W7ZW4498',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnb_CuYYrFO7uozl1XiZ8_ZnCzfT169w',
    appId: '1:39414070165:android:67afc37d266b712f5e149c',
    messagingSenderId: '39414070165',
    projectId: 'monitoreo-apicola',
    storageBucket: 'monitoreo-apicola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAieYQeU15wAHTpg_x7S2XVhmdwBqA9gLk',
    appId: '1:39414070165:ios:2fbb14136226c1255e149c',
    messagingSenderId: '39414070165',
    projectId: 'monitoreo-apicola',
    storageBucket: 'monitoreo-apicola.firebasestorage.app',
    iosBundleId: 'com.example.monitoreoApicola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAieYQeU15wAHTpg_x7S2XVhmdwBqA9gLk',
    appId: '1:39414070165:ios:2fbb14136226c1255e149c',
    messagingSenderId: '39414070165',
    projectId: 'monitoreo-apicola',
    storageBucket: 'monitoreo-apicola.firebasestorage.app',
    iosBundleId: 'com.example.monitoreoApicola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDodHqctL40j39zl9cw09HK0A9pMBwvKGs',
    appId: '1:39414070165:web:b9ea05db165804dd5e149c',
    messagingSenderId: '39414070165',
    projectId: 'monitoreo-apicola',
    authDomain: 'monitoreo-apicola.firebaseapp.com',
    storageBucket: 'monitoreo-apicola.firebasestorage.app',
    measurementId: 'G-TZ9EXS7V2P',
  );
}
